name: hlbmerge
description: "A new Flutter project."
publish_to: 'none'

version: 2.1.4+214

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #路径
  path: ^1.9.1
  # 路由
  get:
    git:
      url: "https://gitcode.com/openharmony-sig/fluttertpc_get.git"
  # 文件选择
#  file_picker:
#    git:
#      url: "https://gitcode.com/openharmony-sig/fluttertpc_file_picker.git"
#  file_picker: ^8.3.2
  file_picker: ^10.3.3
  # 路径
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"

  #url跳转
  url_launcher:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      ref: "br_url_launcher_v6.3.1_ohos"
      path: "packages/url_launcher/url_launcher"

  #包信息
  package_info_plus:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/package_info_plus/package_info_plus"
      ref: "br_package_info_plus-v8.1.0_ohos"
  # ffmpeg_hl
  ffmpeg_hl:
    path: ./ffmpeg_hl
  # 数据存储
  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
  # 拖拽
#  desktop_drop: ^0.6.1
  desktop_drop:
    git:
      url: "https://gitee.com/molihuan/flutter-plugins.git"
      path: "packages/desktop_drop"

#强制覆盖
dependency_overrides:

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^3.0.0
  # app图标
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/app_logo.png"
  image_path_ios: "assets/icons/app_logo.png"
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 24
  windows:
    generate: true
    image_path: "assets/icons/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_logo.png"


flutter:
  uses-material-design: true
  assets:
#    - assets/images/
    - assets/icons/
